version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  php:
    image: php:8.0-fpm
    container_name: php
    volumes:
      - ./php:/var/www/html
    networks:
      - backend
      - frontend

  web:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./php:/var/www/html
    ports:
      - "8080:80"
    networks:
      - frontend

volumes:
  db_data:

networks:
  frontend:
  backend:
